#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 14 17:21:18 2024

@author: vinzoni
"""

from dna_toolkit import *
import time
import random
import requests

def dna(dnaString):
    ''' Ex. 1: counting DNA Nucleotides '''
    a = c = g = t = 0;
    
    for nuc in dnaString:
        if nuc == 'A':
            a += 1
        elif nuc == 'C':
            c += 1
        elif nuc == 'G':
            g += 1
        elif nuc == 'T':
            t += 1
        
    return f'{a} {c} {g} {t}';
    
def rna(dnaString):
    ''' Ex. 2: Transcribing DNA to RNA '''
    return dnaString.replace('T', 'U')

def revc(dnaString):
    ''' Ex. 3: Complementing a strand of DNA and Reverting '''

    return reverse_complement(dnaString)

def fib(n, k):
    ''' Ex. 4: Rabbits and Recurrence Relations '''
    f1 = f2 = 1
    for c in range(n-2):
        litters = f1 * k
        f1 = f2
        f2 = f2 + litters
    return f2

def fibd(n, m):
    ''' Ex. 5: Mortal Fibonacci Rabbits '''
    pairs = [0] * n
    newborns = [0] * n
    pairs[0] = pairs[1] = 1
    newborns[0] = 1
    newborns[1] = 0
    for idx in range(2, n):
        if idx - m >= 0:
            deaths = newborns[idx - m]
        else:
            deaths = 0
        offsprings = pairs[idx-1] - newborns[idx-1]
        pairs[idx] = pairs[idx-1] + offsprings - deaths
        newborns[idx] = pairs[idx] + deaths - pairs[idx-1]
        
    return pairs[n-1]

def gc(filename):
    ''' Ex. 6: Computing GC Content '''
    lines = open(filename, "r").read().splitlines()
    genome_dict = {}
    current_id = ""
    current_genome = ""
    for l in lines:
        if l[0] == ">":
            if len(current_genome) > 0:
                (fast_id, data, score) = (current_id, current_genome, gc_content(current_genome))
                genome_dict[fast_id] = (data, score)
            current_id = l[1:]
            current_genome = ""
        else:
            current_genome += l
    (fast_id, data, score) = (current_id, current_genome, gc_content(current_genome))
    genome_dict[fast_id] = (data, score)
    
            
    max_score = 0
    winning_id = ""
    for k, v in genome_dict.items():
        if v[1] > max_score:
            winning_id = k
            max_score = v[1]
    
    return winning_id + "\n" + str(max_score);

def hamm(dna1, dna2):
    ''' Ex. 7: Counting Point Mutations '''
    point_mutations = 0
    for a, b in zip(dna1, dna2):
        if a != b:
            point_mutations += 1
    return point_mutations

def iprb(k, m, n):
    ''' Ex. 8: Mendle's First Law '''
    
    total_pairs = (k + m + n) ** 2 - (k + m + n)
    mating_dict = { 
            "kk": (1, k * (k-1)),
            "km": (1, k * m),
            "kn": (1, k * n),
            "mk": (1, m * k),
            "mm": (0.75, m * (m-1)),
            "mn": (0.5, m * n),
            "nk": (1, n * k),
            "nm": (0.5, n * m),
            "nn": (0, n * (n-1)), #  superfluo
    }

    good_pairs = 0    
    pairs_sum = 0
    for k, v in mating_dict.items():
            prob = v[0]
            pairs = v[1]
            good_pairs += pairs * prob
            pairs_sum += v[1]
    
    return good_pairs / total_pairs

def prot(rnaString):
    ''' Ex. 9: Translating RNA into Protein '''
    
    RNA_codon_table = {
        "UUU": "F",      "CUU": "L",      "AUU": "I",      "GUU": "V",
        "UUC": "F",      "CUC": "L",      "AUC": "I",      "GUC": "V",
        "UUA": "L",      "CUA": "L",      "AUA": "I",      "GUA": "V",
        "UUG": "L",      "CUG": "L",      "AUG": "M",      "GUG": "V",
        "UCU": "S",      "CCU": "P",      "ACU": "T",      "GCU": "A",
        "UCC": "S",      "CCC": "P",      "ACC": "T",      "GCC": "A",
        "UCA": "S",      "CCA": "P",      "ACA": "T",      "GCA": "A",
        "UCG": "S",      "CCG": "P",      "ACG": "T",      "GCG": "A",
        "UAU": "Y",      "CAU": "H",      "AAU": "N",      "GAU": "D",
        "UAC": "Y",      "CAC": "H",      "AAC": "N",      "GAC": "D",
        "UAA": "Stop",   "CAA": "Q",      "AAA": "K",      "GAA": "E",
        "UAG": "Stop",   "CAG": "Q",      "AAG": "K",      "GAG": "E",
        "UGU": "C",      "CGU": "R",      "AGU": "S",      "GGU": "G",
        "UGC": "C",      "CGC": "R",      "AGC": "S",      "GGC": "G",
        "UGA": "Stop",   "CGA": "R",      "AGA": "R",      "GGA": "G",
        "UGG": "W",      "CGG": "R",      "AGG": "R",      "GGG": "G", 
    }

    proteinString = ""
    codon = ""    
    for nuc in rnaString:
        codon += nuc
        
        if len(codon) == 3:
            protein = RNA_codon_table[codon]
            
            if protein == "Stop":
                break
            
            proteinString += RNA_codon_table[codon]
            codon = ""
            
    return proteinString

def subs(dna1, dna2):
    ''' Ex. 10: Finding a Motif in DNA '''
    locations = finding_motifs_locations(dna1, dna2)
    return " ".join(str(l) for l in locations)


def cons(datafile):
    ''' Ex. 11: Consensus and Profile '''
    
    genome_dict = read_fast_file(datafile)
    dna_len = len(next(iter(genome_dict.values())))
    
    A_count = [0] * dna_len
    C_count = [0] * dna_len
    G_count = [0] * dna_len
    T_count = [0] * dna_len
    for v in genome_dict.values():
        for idx, nuc in enumerate(v):
            if nuc == 'A':
                A_count[idx] += 1
            elif nuc == 'C':
                C_count[idx] += 1
            elif nuc == 'G':
                G_count[idx] += 1
            elif nuc == 'T':
                T_count[idx] += 1

    dna_consensus = ""
    for idx in range(dna_len):
        candidate = 'A'
        count = A_count[idx]
        if C_count[idx] > count:
            candidate = 'C'
            count = C_count[idx]
        if G_count[idx] > count:
            candidate = 'G'
            count = G_count[idx]
        if T_count[idx] > count:
            candidate = 'T'
        dna_consensus += candidate
            
    return dna_consensus, A_count, C_count, G_count, T_count

def grph(datafile):
    ''' Ex. 12: Overlap Graphs '''
    genome_dict = read_fast_file(datafile)
    reverse_genome_dict = {k: v for v, k in genome_dict.items()}
    
    res = []
    for k1 in reverse_genome_dict.keys():
        for k2 in reverse_genome_dict.keys():
            if k1 == k2:
                continue
            head = k2[0:3]
            tail = k1[-3:]
            if head == tail:
                res.append(reverse_genome_dict[k1] + " " + reverse_genome_dict[k2])
            
    return res

def iev(population_str):
    ''' Ex. 13: Calculating Expected Offspring '''
    populations = list(map(int, population_str.split()))
    # genotypes:
    #        AA-AA, AA-Aa, AA-aa, Aa-Aa, Aa-aa, aa-aa
    probs = [1.0,   1.0,   1.0,   0.75,   0.5,  0]
    
    result = 0
    for pop, prob in zip(populations, probs):
        result += prob * pop
    
    offsprings_per_couple = 2
    return result * offsprings_per_couple

def lcsm(datafile):
    ''' Ex. 14: Finding a Shared Motif '''
    genome_dict = read_fast_file(datafile)
    
    first_value = next(iter(genome_dict.values()))
    for motif_len in range(len(first_value)+1, 1, -1):
        for i in range(len(first_value)-motif_len+1):
            candidate = first_value[i: i+motif_len]
            occurrences = 0
            for v in genome_dict.values():
                if (candidate in v):
                    occurrences += 1
                else: # senza questo else fnziona ma ci mette due minuti anziche due secondi.
                    break
            if occurrences == len(genome_dict.items()):
                return candidate
            
    return "no shared motif"

def lia(k, n, rounds):
    ''' Ex. 15: Indipendent Alleles '''
    offspring = "AaBb"
    partner = "AaBb"
    
    good = 0
    
    for i in range(rounds):
        ok_offsprings = 0
        for j in range(2 ** k):
#            offspring = mate2(offspring, partner)
#            offspring = mate2(offspring, partner)
            male = offspring
            female = partner
            offspring = male[random.randint(0,1)] + female[random.randint(0,1)] + male[random.randint(2,3)] + female[random.randint(2,3)] 
            if offspring == "AaBb":
                ok_offsprings += 1
            elif offspring == "aABb":
                ok_offsprings += 1
            elif offspring == "AabB":
                ok_offsprings += 1
            elif offspring == "aAbB":
                ok_offsprings += 1
            
        if ok_offsprings >= n:
            good += 1
        
    return round((good / rounds), 4)

def mprt(datafile):
    ''' Ex. 16: Finding a Protein Motif '''
    
    proteins = []
    with open(datafile, 'r') as f:
        for line in f.readlines():
            proteins.append(line.strip().split("_")[0])
            
            
    fastafile = datafile.split(".")[0]+".fasta"
    protein_database_url = "https://rest.uniprot.org/uniprotkb/PROTEIN.fasta"
    with open(fastafile, "w") as f:
        for protein in proteins:
            url = protein_database_url.replace("PROTEIN", protein)
            response = requests.get(url)
                  
            if response.status_code == 200:
                f.write(response.text)
            else:
                return f"Errore nella richiesta: {response.status_code}"
            
    # N-glycosylation motif is written as N{P}[ST]{P}.
    N_glycosylation_pattern_len = 4

    protein_dict = read_fast_file(fastafile)
    motif_dict = {}
    
    for k, v in protein_dict.items():
        motif_dict[k] = []
        for i in range(len(v)-N_glycosylation_pattern_len+1):
            sliding_window = v[i:i+N_glycosylation_pattern_len]
            if "P" in sliding_window:
                continue
            if sliding_window[0] == "N" and sliding_window[2] == "S":
                motif_dict[k].append(i+1)
            if sliding_window[0] == "N" and sliding_window[2] == "T":
                motif_dict[k].append(i+1)

    retval = ""
    for k in motif_dict.keys():
        if motif_dict[k] == []:
            continue
        protein_name = k.split("|")[1]
        motif_locations = ' '.join(str(x) for x in motif_dict[k])
        retval += f"{protein_name}\n{motif_locations}\n"
    return retval

def mrna(proteinString):
    ''' Ex. 17: Inferring mRNA from Protein '''
    
    reverse_RNA_codon_table = {
        "F": ["UUU", "UUC"],    
        "L": ["CUU", "CUC", "UUA", "UUG", "CUA", "CUG"],    
        "I": ["AUU", "AUC", "AUA"],    
        "V": ["GUU", "GUC", "GUA", "GUG" ],    
        "M": ["AUG" ],    
        "S": ["UCU",  "UCC", "UCA", "UCG", "AGU",  "AGC" ],    
        "P": ["CCU",  "CCC", "CCA", "CCG" ],    
        "T": ["ACU",  "ACC", "ACA", "ACG" ],    
        "A": ["GCU",  "GCC", "GCA", "GCG" ],    
        "Y": ["UAU",  "UAC" ],    
        "H": ["CAU",  "CAC" ],    
        "N": ["AAU",  "AAC" ],    
        "D": ["GAU",  "GAC" ],    
        "Q": ["CAA",  "CAG" ],    
        "K": ["AAA",  "AAG" ],    
        "E": ["GAA",  "GAG" ],    
        "C": ["UGU",  "UGC" ],    
        "R": ["CGU",  "CGC", "CGA", "AGA", "CGG", "AGG" ],    
        "G": ["GGU",  "GGC", "GGA", "GGG" ],    
        "W": ["UGG" ],    
        "Stop": ["UAA",  "UAG", "UGA" ],    
    }
    
    count = 1
    for c in proteinString:
        count *= len(reverse_RNA_codon_table[c])
    count *= len(reverse_RNA_codon_table["Stop"])

    return count % 1000000

def orf(datafile):
    ''' Ex. 18: Open Reading Frames '''
    genome_dict = read_fast_file(datafile)
    dnaString = next(iter(genome_dict.values()))
    
    DNA_codon_table = {
        "TTT": "F",      "CTT": "L",      "ATT": "I",      "GTT": "V",
        "TTC": "F",      "CTC": "L",      "ATC": "I",      "GTC": "V",
        "TTA": "L",      "CTA": "L",      "ATA": "I",      "GTA": "V",
        "TTG": "L",      "CTG": "L",      "ATG": "M",      "GTG": "V",
        "TCT": "S",      "CCT": "P",      "ACT": "T",      "GCT": "A",
        "TCC": "S",      "CCC": "P",      "ACC": "T",      "GCC": "A",
        "TCA": "S",      "CCA": "P",      "ACA": "T",      "GCA": "A",
        "TCG": "S",      "CCG": "P",      "ACG": "T",      "GCG": "A",
        "TAT": "Y",      "CAT": "H",      "AAT": "N",      "GAT": "D",
        "TAC": "Y",      "CAC": "H",      "AAC": "N",      "GAC": "D",
        "TAA": "Stop",   "CAA": "Q",      "AAA": "K",      "GAA": "E",
        "TAG": "Stop",   "CAG": "Q",      "AAG": "K",      "GAG": "E",
        "TGT": "C",      "CGT": "R",      "AGT": "S",      "GGT": "G",
        "TGC": "C",      "CGC": "R",      "AGC": "S",      "GGC": "G",
        "TGA": "Stop",   "CGA": "R",      "AGA": "R",      "GGA": "G",
        "TGG": "W",      "CGG": "R",      "AGG": "R",      "GGG": "G", 
    }

    startCodon = "ATG"
#    strands = [dnaString,                           
#               dnaString[1:],                       
#               dnaString[2:],                       
#               reverse_complement(dnaString),       
#               reverse_complement(dnaString)[1:],   
#               reverse_complement(dnaString)[2:]]   
    strands = [dnaString, reverse_complement(dnaString)]   
    
    proteins = set() 
    startCodon = "ATG"
    
    for dnaString in strands:
        locations = finding_motifs_locations(dnaString, startCodon)
        for loc in locations:
            codingSection = True
            protein = ""
            codon = ""
            for nuc in dnaString[loc-1:]:
                codon += nuc
                if len(codon) == 3:
                
                    aminoacid = DNA_codon_table[codon]
                
                    if aminoacid == "Stop":
                        codingSection = False
                        break
                
                    protein += aminoacid
                    codon = ""
            # se codingSection e' true significa che e' finita la stringa prima di incontrare un codone di stop e allora non vale.
            if codingSection == False and len(protein) > 0:
                proteins.add(protein)
        
    return '\n'.join(proteins)

def perm(n):
    ''' Ex. 19: Enumerating Gene Orders '''
    
    dataset = [x for x in range(1, n+1)]

    perms = permutations(dataset)
    
    result = f'{len(perms)}\n'
    for p in perms:
        result += f'{" ".join(str(x) for x in p)}\n'
    return result

def prtm(proteinString):
    ''' Ex. 20: Calculating Protein Mass '''
    
    return "100.2"

print ()
print (dna.__doc__)
dnaString = "CATGCGAGACATTATACACTATGGCTTGGCAGGCGAAGAATATTTCTTGGGATTTCGGACGACCACATTTCCGCCACACACGCCGCGTTGAAGCGTCCTCACGTCACGCCGTTACATTCGTATTCGCTCTAAGCGCCTCCATCACAACCTGTAATACTCTATGAGGGATCAAACCAGGTGCTAACCAAAGAACCAATCTTGCACAGCCGTGTAGGTGGTTCGTGGGAATTACCCGGAAACAGCCTAGAAGAGCATAACCACGTATCGTCGCGAACTGTGTCCATTTTCGTCGCTCAACCAAACACTACTTCGTCGAACTTGAGCGGTGCGACGGCCCTATAAGTACCTTGTATGCCGCTAGGAAGATACCGAAGATCGAAACAGTTATCGGGAGGCAACTGTGTCGTTCCTTACATGTGAGAAAGCACCCCGGAGGGGTGTACGCATATCATGGCCATCTGCGGGGCGAATTGATCTTTAGACCCCGCTTACCCCACGTCGCTTTCCGTCCTTCTTCATAAGACCCCTAAGGGTATGTCCGGTTACAGTTTACGCCACTTCTGCTCGTCTCGATAGTAAGTCTAGCGTCGCATGAGAAAAAGACCTCCGCCGGTACAAATGCATCTAAGCCAACGCGTAAGCACCAGAGAGTTTAATCCGTCTCCGGGCTCTCGAAGCTATTAGTGCCGCGCGGGCATTTAACAGTCAGTAATAGCTCACCCCGCATTAGATGAAGTATGTCACCTCTAACGGACTTCGCATCTCTTGTGTTGTCCAGACTACAGACACTCTAGACAGAAGCCCCTCTGGCGGGCTTGGTGCAGCGCTGGAGTC"
print (dnaString)
print (dna(dnaString))

print ()
print (rna.__doc__)
dnaString = "CCCAACAGGCATGTGCGATGAATTATGGTGGCAGGAGCCATTAATAACATCGCTGTGGCCCAACCGGGATGTTGAGAGTTCAACCGATTTCGGCAAAACAAAGACACAGACGAGTTTTGTTTGGGAGGTAGAGCGAGAAGCCCCCATGCCGGATCCATCACCCGGTCTGTAACTTTTTAGGATAGGCGGGCGTGGTCTCCGCATTATCATTCAATCGCGGGTGCCGTATCTCGCCGTCGTTGCATCCCTTACAGCGGGACCAATACACGAACCAGTCCAATCAGGCTTGCTTGATACGCAAAATGTACAATCTATAAATTCGGCTACTAGCATAGCCGAGCCCCCGTAATGGCCTTATACCGCTGGAACGTTCATCTCGAGGGAGGGCCGTGCCACAAACCCGCGGAGCGGTGGCCGTAGATTATACTAGAACTAAAATACATCCTCACTACGGGTGTCGTGGACACCAAACTGAAGGTTGTTGAATACGCTTCCGGAGTAGGGTTCACTATACCTGGGCGAACATCAGCCCGAGCATTGCCACCAATCAAACTAACTCAAAATGACTACTATGTTAGCCTCCGGCGAAGGGGAGTCATTTTCCAATCCTGAAGATTTCCCCGCCCATCCTCGCTATTTTCTCATATCTCAAGAATCCCATGCTTTTTAAATGCCTATGAGAGTGTGTAGGGTCCCTTCTTTATCCTATAGTATCGGCTCCACGGTGACCATGCATTGAAGAATTATTAATGATTCACGGCGCCCATATAAGTCACGTGGCGCGCCCTTCTTGGTTTCATACGCTCCTCGCGCTTGTTTGAGAAAGAAGCAAGTCAGAATTCAGTATATGTTTACAGTCGTGGCGCAGGTACTTGCAACTCGGGTAGGCTACGCTGCCGCGTTCGAAGACACAAATCTACTGGTTACCTATCTGCAAACCAATTGTTAGGGTAGACAGCCGAAACTAGTCTAACCTCAGTAAATAG"
print (dnaString)
print (rna(dnaString))

print ()
print (revc.__doc__)
dnaString = "AAAACCCGGT"
print (dnaString)
print (revc(dnaString))

print ()
print (fib.__doc__)
n = 36
k = 3
print (f'n = {n}, k = {k}')
print (fib(n, k))

print ()
print (fibd.__doc__)
n = 96
k = 18
print (f'n = {n}, k = {k}')
print (fibd(n, k))

print ()
print (gc.__doc__)
print ("datafile: gc_dataset.txt")
print (gc("gc_dataset.txt"))

print ()
print (hamm.__doc__)
dna1 = "ATGTACTGGTCAAAGTGTAGTTTACCTATCCTCAGTGACTGAAGGGCTATCGCGGTGTTGATTCAGTGGCATGCGGGCAGCGTAAGGACACAGATATTAAAATCGGGGAATCGTGTATGTGATAAAGGAACCGAGGGAATTCCAGTCAGCCGGCTCAAACGCAATTTGGTGGGCTTTGTGTCAAAGTCATAGTGCAGTGCGGTGCACGCGTTTAGACTATATGCCCTCTGAACTGTTAGGTTTGAAGAAGACGGGACGCGGAGTGAGCGAACGCTTTTAAAGATTGCCGTCGGTCCTCGGCGGGCCATCTGATCTGAAACCTTCTCAGGGGCCATCCTAGGCCCAAGACGGTCCACCGCTAACTAAGAGATAGTGCGATCGCGCTGTAAATGCGTATCTAGTGTGGAGATTGAGGCAGGGATCCCCCATTACAACCAGGGTCGCCCTGCGTCCACGACGCCTGGGCTACCGTTCAATGTGCACTCTGACCGGGAGCGTCCCTCTCGTGAGGCTAAATTCAGTTCTAATCGGTAGGGGAGAGAGTACATGTTTCGAAATCAGATGTACGACTTATTAAGGTCCTCTCTAATCCGTAGCCACACCAAAGTATTCGCCGATTAGGAACGGCAATCGTAAGACATTGTACTGCCCCCGTGCTGGTTGTCGCGTATAATGGCGCATATCGCGACACTGCCCTTATATAGCCATACACGAACGGTCCAAGTTTTAACAGAACCGACGTTGCTCTCTAAATTAGTGCTAATGGAGAGTAAGAACGAAGAACGAAGCTCTTTCCGCGAGAATATGTGAAAGCATCAGTCATCTAAGAACCGTTAGTGGTAGCGAAGTCTGCAAGCCTTCGGAAGTTCTCCAGATGTCGGCCCTATGCTCCACAAACGCGACTACGCCTGTGCAACTAAACCAGTCGG"
dna2 = "TAGTACCGATCAAGATAGGGTTTTTACATCGTCAGTCGATGCGGTCTTATGCCCATTTATGCTGAGTTTCCCAGCGGGAGATACTGGATAGAGCTATTAACTTCTCGGAAGCGTTGATGTGACCCAGCGGATTCGCGATCTCGAGGCTCTCCTCTCAGCCTCTTAGTGGTGCGAGCCTCAGTACATCGGGTAAACGGTCTGCGGCCCGCGTTTTGTCGATGTGGCCGTGGAAAGGATCCGTTTGTCTTAGACGGAAGGTTGATCTACCGGACGGCATTCAGGGTAATGCTTAATTTTCTGCTGATATTACCCAGTGTCACCGACACAAGAGCTTTCCTAGCCCCAAGACGTTTGTACCTTAACCACGTGTATGTATTAGCCTGCCGTAGTTTGGAATGAGTTGTATAGCAAGAGGCAAGTGTCCTCCACGACCAACTGGTGCCCCTGACGGCCAGGAACAATTTTGTTCAGCGCCGTATGGTCTCTGATTACCAGTTTGCGCGTCGTATGCAGAAGCACCAACTGACGTCGTGACATAGAGAGTATTGGTGTCTGAACGTGATGGAGTGATTCATGTGTATCCGTCTCTAGAGCTCGTCCAACATATCATCCGTCGATTAATGATAGCACAGTGCACCGAGAGTATACCCCCCGTACAAGGTTTGGTATTTAAGCGAGCATGTCCACAGAACGCACATAGGCACCCCAACTCAGCCGACCCAGGTTTCAAATTACGCGGACTTCCTTTACTCGTGTGTATTGTTGGACATGTAAACCATACAACCAACACCACTGTGCAACAATATGAGCAACTACCGATGTGCCCGTACTAACGCGAGCGGGAATAGTCGCCGAGGATTGACCAGTACTCAAGTTGACGGCTCTATACTATACAACGGCGACTACGCCAGGATAACCAAAGCTTTCAT"
print (dna1)
print (dna2)
print (hamm(dna1, dna2))

print ()
print (iprb.__doc__)
k = 17
m = 16
n = 15
print (f'k = {k}, m = {m}, n = {n}')
print (iprb(k, m, n))

print ()
print (prot.__doc__)
rnaString = "AUGUGUGUCCCUUUAACAUCUAACAGAAUGUCCAUUUGGAUUGUGCAAUUAUCACCGUCGGGGCGCCCAGACCGUUCCUCAUUCCAAUGUGGCGAACGACCGGACAUCAAGACGCCGUGGCAUCAUCUGCACUUGUUAGCGAAAGAUCGUAAGUAUCUGGGAAAGCUGCAAUCCAUCAGUGGUGCUCACAGCCCCCCACACGGUAUGUGCAGGGUCCCAUACGCUCCCUGUGUAUGCGACUUCGCACUUAGGCCUCGAGUAGGACUAGGUCAAGUGUGGGAUGCCGUAUUGCACAUAUAUGUACGGGAGGUGUAUGCGAGAGGAAAUGAAUAUGUUCUUAUAUACUUUAGGGCCUCUACCCAUCUACAUUCCCUUUCGCUGACUAUUCUGGCUCCUUACCUCGGAUCGAUUGUCGAAUUCGUCUCUAUUUGCGCAGUUCAAGGUCUAAAAAAGCGUCAGGUUGACCCUGACGUCUAUUCACACUUGCAUUCAAGCCCUGUAUGCGGAUACUUACCUCUAGACUGGAACCUUCAAGGUAAAACUCGACCAAUUAAAAUCCCAGGAUCUACACACGGUGACGUCCUCUUGCAUACCACGCAGUCCGCAGGAGUAGCCCUUAAUGGUGUUAAUGAAACAGACAAUCUUCUCAUGCCUUUGCCUCAAUUAUCAGUAGGAUAUCCAGGAAAUCUGAGCGCGGUACCCCUACGUACUAGAAGCUCGAUGCUCCUAAACAUCCGAAGCUAUCGGCACCGGAGUAAGAGUAGACAACGAGGAACCAGAGAAUUUACGACAUGCCCGCAUACCUAUCAGGCCCGUUCUUCGGUCAGAGCGGAAAGGCGCGGACAUAACAGGCCUGGGCAUUUCCCCAGGACACUACUGGCGAUUCCAAGAGCGGACGCCAAUCGGCCUACACCGCCGUUCUGUAAAGGCGACCAACUUAGAACAUGUCUUAAGCAAGCAGCGGCCUUCAGUUCUGCGCGCGUGUUUCAAAAAGCGGAGUACGCAGAAGGUGGGAAUACGCUUCGUACGGUUAUAUUUUCAUACAUCCCUCCGACAAGUGUUGUGGUGUUAACUACCUGUCUCUUAAGGACAACUUCAGUUUCCAGUCGGAGUGGAGAGCGUAGUCCGCCCAGUGUCCCUGCUCCCGUUACUGAUAACCUCUCCCACAGGGCGAAACGGAGGUGCGGCGUUACUUCCACUCCCACGAUGCGCGGGGCCCCGGGACGAAAAACAUACGCCGUUUAUUGCGUCGACAGUUCCCUAUUCUGCCUGUGGUGCAUAAAACCGAGCACGCAAAGUCACCUAAACUUGCUGGAGCCCAUCCAGGGAUUUUCGAACCUUGGUUCUGAGGAGUAUCUGCGUAACGGGUAUGUGCUUGUACGGCUUCGGUACGGCGACUCGUUACAUCUGGUAACUGCGCCUAGCCUUCGUAGUGUAGCAGACUGUUGGAGCUAUAGCAAUCUCCACGAAGUAAACACUGCGCGUGGCCGGCUAGUCGCGCUCGCCUCCAAUAGACUAGAUUACGCCGGCGGACCGUUAUUAUACAGACAUGAGCGAUUUCACGAGGCCAUCAUGCGGAGAGAGAUGACGCUCCUUUAUCACCAGUGGUGGGAAUAUACAAUUACUGAUAAGCCCGGAACGGCGAUGAAAUACUUCGUCAGGAAGAAGCGAUGGCGUGCUGCCGAACGUCGGAAUAAGGUGCUGGGUUGCUAUCAUUUAGGUGACCAUAUAUAUAUUAAAACUAAAUACCGCCAUUCCAGGUCCAGUAGGGGCGGCGUCCGGAUGGCGUAUCAGUCAAAUUGGGCAUACACUCAGCGGCAUCAAACUAAGCCGCUUGCGUUGUACAAACCUUCGACAGAGGACCGUCGGAUCGACAGAACGCGACAGCCGUGGGAUCGUUCACCAAGAGGAUGUAGGCGCUAUAUUUACAGGGGCAACGAACCCCUGAACACUGGUAACAUAUGCCUAUUUAGCACCUUUAUGCAUGACCUCCAUGCACUUAAUUCUUAUGGGCGGGGGGCCCUAGAGAACCACUCGUGUGCAAUAUUGGCUCUACACAUGCGAGAGCAGGUGGCCUCCAUGGCGCCUCAGACCAUAGUCGCACCCAUCAACAAUGUCGUAACGUGUUCGGAGACCAUAUUAGACCAUAAACCAACUUGCCGAUGGCCAGACAUUUCAUUUCCGCGACGGAGCGGAUUCUAUCUCAUUUUGUCCAAUGGCUCCUCAGUUAGGAUAUGGUUGCUCCUCCGCACAUUUCAUCUUACUUUGGGGCAUGUUGUCGUCUGCGAGAGUUUUCCGCGAGCGUUGACUUCAAGUGCGUGUCCAGCGCUGCUGGAUGGGGGUAGCCGUAAUCUGGCCCCGUCCUUGUUCGCUCCGAGUGCCGUUGCUUAUCCCGUGUACUCUAUCAACCUACCUGGGCGCAAUUGGACAACCGCAACCAGUUGUUCAGUACGCAUAACUGCCUACAGCUAUGCUUCAUCUGGCUUAGAGAGGCGUUUGGUCAUGUUUCACGACUGUCGACCGAGUGCUCGUACUCUCUUGUCCCGCCACCUUAAGGCUAGUUUUGGGCUAGUCGCGGUUGGUACGCCACUCGGGAAACGCCCCAGAUGUGCCGGCCGCGCACCUCGUACCUGCCCUUGUACUCUUGUAACACUAGCAAAGCCGAUGGUGUUGCCUUUUAUACUGUGGCCCACCGCGGCCACCGCGUCGAGUUUCCGUCCUUUGCCUCAACGGAAAUUUCAAGAGUAUGAUGAAUACAUGUGCCCGCCACUAAGGCCCACAGAGCUACGACACGUGCUUAGAUCCGACUCUGGCCCGGUCCCUGAAUUGGAUGUGGUAGCUUUGGUGGCGAUUACAGUGAAGCUAACUCUAGAAUCGGCACCUACGCAUUCCCGCAGGUAUCCUCAAACCAGUAAUGGCCCGGUUAGGUUUGAAAGGGUCAAAUCUGGCGCUAGAGAACGCGCCUCAAAAAAUAAUACACUUUUCCGAUUCGACCAAAGAACGAUUCCGAAACCGUGGCACAAUAAUGCGCUGUCGUGCCCCGUUACUGCUCUUCCGGCACUCAUGGGCACCAGUUAUAGACACAUCGCCUACUCUUCUACGAGCCAUCGGUGCCUACUGUCGAGAGGUCAGCCCCCGGGCGCAAUAUCGCAUCCGCAUCUCACUUCACUUUCUCUAGCAAUAUGCUGUCAACGUUGUAAAGAAGGACCUGUUGCCGUCUCCGGUAUGCAAUGUACCCCUCAGGCAGUGCCAUGCCUGGGUUAUAAUCCACCGUGGCUAUUAUCUGGUGCCGGCCCCAUAUCGUUCCGCACUUACAACGUGAAAUCUCGUUCCGUUUACGCCUUCCUGAUUUUCUGCGACAGACACCACGUCACCCUGAUCCCGGAAAUCGAAGAAACCUUAUGCCAGUGGGAUUUCGCGUGGGUAGACACACCAGCCACCCCUGCAACUUUUUACAAUACUCUAUUACGGGCUCGUAGAUGCCUGGAACCGCCUUUUCCAAGACCGGGGGUGCAUUACUCAUCCAAAGGAUCGCCCAAUUCGCGCCCGUAUGUAUCAGUUGCCUUGUUGCAACGGGUUCUUAUCUUUCUCAACUUUGAGGCACCGCUGCCACCCACGUAUCUUAGUGCGAACAACCAGCUUACUAUGCUCAGGCUCGGUUUUGCGACAUUUUCCUUGGCCACUUAUUGUGCCCCCACGCUGCCGUUAGUAUACAUGACGAAUCGCCCGUUAGCCCUGCCGGGAGAUCCUGGAGGCUGUCACACGCGUAAUCGUUGCGAUGAAGGUCUAAGAAGAAUCUGCCAAUCCUCAAGACCUGCAUCGAUGCUGUGUACGUAUUAUCUAUUGAACCUGUUUCCCCCCUGGCGCAGUUCUGCCGACCUUGUGGUUGCUACUACCCUUCGAAUAUGUCAAGAGUCCCCGUUUACUGUGUGUCUAGAGCUUAGUUCAAGGGCGGAACCGGUUUACGCGUCUCUUGUGGAUGCUUUAUGUGGCAACGGUACCUCCCCCGUGCUGAUGUUCUCUGAGUUACCGGACGCGAUCCUGAAACCUAACCCAGAUCAGACCCGACGCUUGGCAGUGGUUUGGAGUGCUCUGUUCCAAGAGCUCUGUUGCACGCUUCAGAUGUCCGUCGGCUCAGACGUGGACCCUUGUGAAAUCGUUGCAAAUAAACCAAAGAGCAUUACGGCGCACGAACGUGAGUUCAACUAUAUAAUUAGUCGGUGGAAUGACGCCCUGUUUUACUCACUUUUUCCUCCACUGAUCAGUGGCUAUCCGGGCGGCUUGUCUAAACCAGCUUCGCCCCCUUUCUUGAAUAGCCACCGACGAUUGACUUCUUGCAUGGCAAAGGGUGCCGUUUUCCUAGUGUAUGCUCCGAGCGCAAACCCUGGUCGAGGCUAUUUACCGGGCAUAGACCUUCAGAGACGUGUCAUAGUAAGGAGUAACGCCAUCACAGUUCGGAACCCAGGAAUGCCAUUGGCAAGGGAUGUUCUCCUGUUCUGGUCGUUCGAUAAGUCUACUGCUACGUCGCUGGUUCUCAGGGGCAAUACGCUGGUGCCAAUUAAAGUGUCCAAGCAUUGUAUCCCGGUUAUAUCCACAGUUAGUGUGCUGUGUAAAACCAGGCAUUCGACUACACGCGGAAGAGCUAAGUGGUUCUGCAGGGUAGUAUGUGCUGCUAGAUCAGUCCAGUCCGUGGGCCGUCGGCUUGCAGAUCACAGCUCUUCUGAUUGGUUAGCAGAACGAUGGCCUAGACAGCGGCGACCGUUACCCAAGUAUUAUUUUGGACCGAUCAGGCUAUACCGAGCUGCGCCCUCUUACAUUCGUGACUAUGUGUGCAUGCUCGAGGAGGUUAGUUAUAAGGAGGUCCAUAAGACAAGUUCAUCUUCUCACCACAUUUACGGCCAUUAUACCAUGAGUCACAUACCUGCCUUUUGGUUGCAGGGAGCUAUACCCAGAAGUGUCAACCUUGGCGACCUCACGAAUCGUCCGCGUCUAGUUGCGUUCAAAAGGUAUUGCCGCACGCUCCGCCCCUGGAACCGUAUGGAAAUAGAACAAAGGGGCUCUCCCCGUAAGCCGCGCUCAACUCCUCGGGCCCCUCGCGUAGCGCUCAAGUAUGAAUCCGAGUAUCGCUGCGUUGUUGCUUGGAACAAGACCGCCGUGCAAAACCCAACUAUAGGGACCCUAAUCGACGCUAUACGCUUUUACCGCUCAUUGCCACAAGUGAUAAAACAGUCCAUACCGGAGAGGGAGUGCGAACAGAGGCCAAGGGCUGGUCAGUCGUCUCGUUGCAGAACACGAUCAACGAAUGCGCGGGAACUUAGGGGUCCCCACAUUUCGAAGUUCGGUCAUCACGCUGAACUCUAUGCCAAUGUAAUAUUACAGCUCACCGGAGGACGCGUUGAUGUGUUAGCUCUAUUUAAAUUUCCACUCGCGGGGACUAUUAAGGGAUUAGGCCGGGCUGUGGCGCAAUCGCAAUAUCUGGGUGACGUUGGCCAAUUUAUUCGCCCAAUGGACUACUUCUCAUCAACACGCCAAUUCUAUCGUUCGAGAACCAUGGAGGGCCAAGAGGCCGCAAUGGCAAAGAACGCCAGCCAAGACAGCAGGUCUAGGAGGGAGCUAAACGGGAAACAACCAGUGGGGCCUAACUUGUUGGCUCUAAUUAGUUCGUUCCGGCAAAGGGUAACUUCCGGCGUGGAGUGUACAGGAAUCACGCGCCACAGCGCCGGCGCGGAGACAUCAAUUUAUGCCCGUCUCACGGGUACGGGCUUUCGCUCUUUAUUUUAUCCGUUAUUGGAACCAUGCGUCGGAAUAUACUCAAGCCUACAGGGUGGAAUCGUGUUCCGCAGCUCGAUGCGCCCCGGUGUCGACCUAAUACGGACAGAGACACUGCGUACACCCCAGGCACCUAAGGCAUACACAUGCCAAGUACCCCACGCUUGUUAUGAGCCCUGGUUGGGUUACGGACCUUCGUCUCGGCUACGUGCACGCAAUCGAGUCUGCUAUCCAUGCCUACCAACCCCAGGCAGGCGCAGCCCGAGGGUAACAUUCCCAUCAGUGCAGAACCGUUCUGGGCCCAUGGUCUACGAUGCUGUAAUAUACCUAGCCAGUUGGGCACAAUCAUGCCAAGGGUGUAACGUACCGGAUUUCCAAGUCAUAGGAAGUAAAAUGGGGAGCUUUUGUUGGUUCUUUGAAUUGUUAACUCAUGUUUACCAAAGUGGACUUACCGGGUCAACGCGUUAUGACGGCUAUUUAACCCCCCGGUACGCGGCCCCUCUCAGGAAUGGAUCGCUGAAAACAGGCCUACGAGUGAAGGAAGACGUCGUAACGCCGGAGGAUGGACUUUGUAAUCGGGUAACUCUAAUACAUUUCAGAGACGACCAUAAGCUCAGGCUCCUUAAGAUGAGUAGACACAUAGCCGUACAGGGGGUUCAUUCCUUCUGUUUCCAGCUCAGUAAAAUGUACUACUCGGUUCAGCAUGCACCCGCUAAGAGGAGUGGUGGUAGCCAUACUCGGACGGACUACUUAAGCCUUCCGGAUAUUGUUCAACCAACCCGACAAAAGCUUGAUAACGUAAAAAUCUUUAUAACUAGUAACCCUGAUCUUAACGGCUCCGUCUACGGAAAAAGGCGAUACUUCGGAAUGUGGACACGACUACUGUUUGGGAAGACGUGGUUGAACACACUCUACCAAUAUGGAGGUAAACCGUCGACCCAUGUUGAAUUUCUAGGGAGCAAUGGAAGGGACCCGGAUCCCUUGCUAUCUGGUAAGAUGGGGAGAAAAAGCACCUUCGAAUCAUCAAUCGAGUCGUCCUCGGCUCAUGGUAUACCUAUGGUCGGCCCAUGUAGUUCGGCUUUAGCUGUGAAAUUUCCGUACUGGGUGGUGAUAGAUUUAAGUCGCGAAGUAUUCUGGUCACUCAGAGGCCCGCGUAUCGUCGGUAAUGUACGUAAAUCGCACCGAUUUUUCUCAAAUUCCUUAAUACAUGGAUCGUGUCCACCGAUGGCGCUCCUCUCGAUCUCAUAUAUGGCGAUUGGCGGGAACAUGUCAAGCCAGCGGCAGCUCAUGCAUUGUAACAAUCGUGCACCCAAACAAGGUGCGUUAUCCCCGACUACAUCGACAGUCGCUCAGCUACCGAAUGCCCAUGGCCUAUGCGUCGCGGUCUCGACUCCUGUAUACAUCGGUAUGGAUAAGAUGCAGCUGGUCAUAAGUCCCAGUGCGCGUCACAUUAGAUUACUGUUUCACGCCUGUCCCGCCCUAGCUAUUACCCAGUAUACAAGGCUAACGCGCUCCACGCAGCUCAACACCGGGGAGGCAGUAACAACUUACCAUGCAUAUGCGUACUCGACCUCUCUAUGGUGGACUACCGAGCGAUGUAGACUCAAUACGCAAGGGCUCCAACCUUUACCACUCUGUCUGUCUACGCGAGCCUCCAACGCCGCAGAGAGUAUCGGAUCACUAGAAUCAUGGUGCGCGACUACUUCAUGUUCGGCUUGGACUGGGCACACGUACGAAAGUCUUGUCCCAGCCGAAUCGGCAAGUCCCCCGUUAAAACCCUAUCCUCGCACGUCGGUAUAUGCAUGCGCAGGCUGUCCCUAUUAUGCGAACCUUCUUUCGCCGUCGUAUGUGGCGACUAGACGUCGGUUUCGGUUCUCUUUCUUCCUAAUGUCUCUGUUCAGUAUCUUCCAUUGUUGCCCUUCCUUCCUCAUACAGAGUCACAAUUACAUUCGACGUAUUAGCCGUGUAGAGGAUAGUCGUUCAAUCAAUUUGCCAGGGGCCCAAAGCCUUCCUGGGCCCAACGUUGAUCCCCGAGAACUUAAAUAUUGUCCAAUUUAUGUUGUGGACAAGUCGUUGACGCAUACUUUGUCGGACCAAUCAGGCGGUUUAGACAGUGAACGGGCUAGUGGACCGAAGCAUUACAAAUUCGUGCCUAAUAUAGACAAGGCUUGUUUGCAGCUAUUGAAGUGUACUGCACCUCAAGGGAGUGAUAAACGCCUCGGUACUAGGCCAGAUCCUCCAUUCGAUAUAUUCAUCGCGUACCUUCAUAACUAUAUCGUACACAACACACAUAAUUACAGCACACUGCGGCAACAGACUGGAGUUUUACGCUGUAAGCCUCGGAAGCCGGUACACAAUUCCGUAUCGCCCUCCCUGUGGUGGUCGUGUCUGAAGGACGCAUCAACGCUUUAUAUCAGUCCCAACGCAGGGCACUUUGAGUGUGGUAUAACGUUUAUAGAGAAAUCGUGUUCUGAUCAUCCUUUGAUCGGAAGUGGCUCGAAGAUGCGGGUUGGCAGCUGUUCCUUACCAAGCUUUCUAACGACGGAGUUUAUACCGAGAUGGGCAGGUCAAGACGACAGUCGCUUGAAACUAGGACAGUGCAUCUCAGGGUCUUCUACUAUGGCUACGCGCCAGGAAUUCCGGUUAUUAGGAUUUUCGGGCAAUAGAGGGGGUCUCUACAACCUGUACAACAUGUUACCGAAUCGAUCGAGCGCCCGAUCCUUGUGUCGUGAAUUAUCCAGGCAGUGCUCGCCUGCGAUUAGUGGACAUGACCGUAGGGACAAACCUGUUGCCACCACUAAAUUGCAGAAUUACAGUGCAGAUAGCACCGCCUGGCGACUCUCAGGAUGUAAGAUUCUCGACCCAACCCGAAUGUUGGGGGACUCAUUACGCGGCUCCCCGAAUCAGUCCAUAGCCCCCUCAGUCUAUGCGAACCCGAAUGUGGUUAGCGGUAAACUAUUCCCAGCCGGUCAGUUGUAUCACGAGGUUUUUUUAAAUGUUGGAGUUGCUCCUGAAUUCACGACAAUCGGGCGCAACCACGGCGUUGCCGACAUAAAAUCAACCGAUAUUCGAGUCGGCUGGCAGGUUUUUACCGCAAGUAGGUCAGCUUAUAGGCGAGAACAACUCCUCACGCGCUAUCAUUUAGAUACUAAUUACUGCAUGGGCUCGUUGGUGUGCUUACGGCUUAUUUGUUUUCACACGUACACGAUUGACGGCCGUCCCGAGAACUACGAUUUAUUGAACAGGUCCCGUGCACCUGAUGAUAGGCCAUCGGGAUGCGCAAGCGCUAUACAGGCCUUCCACCAUAGGCGUGUGCUCAUUUCUCCUCACUCUAGUAGUCAAUGGAGCUGGCACAACUCCGAAAAGCCUGUUGUUCCGACCGGCGGUCUGGAUCAGCAAAGUGCCUGCCCUCGUCCAGUGCCAGGUCUGGGAACUCAGAGUUGA"
print (rnaString)
print (prot(rnaString))

print ()
print (subs.__doc__)
dna1 = "CGTATGAACCGTATGAAATCGTATGAGGCGTATGAAGCCCGTATGAATCCGTCCCGTATGACACGTATGATGTCCCGTATGACGTATGACGTATGACGTATGAAAGCGTATGACGTATGATCCACCGTATGAGACGTATGACGTATGACACGTATGACGTATGACGTATGAGCGTATGATCGTATGAGACGTATGACCCGTATGACGTATGAAGCCTCGTATGAACGTATGAGATCACGTATGACGTATGACAAGGCGTATGAATCGTATGAATACCGCGTATGATGGAGTCGTATGACCGCGTATGAAAGGCTCGTATGAAGCGCGTATGACCGTATGACGTATGACGTATGAAACGTATGACGTATGAGCGTATGATCGTATGACCGGCGTATGAGCCATTTGCGTATGAACGTATGAGCTCTCGTATGAATAACGTATGATGACGTATGAGGTCGTATGACGTATGAAGCGTATGATACGTATGAGTTACGTATGACAGCTTCGCTTCCGTACGTATGATTCCGTATGAGATCTCCGTATGACGTGTCGTATGAGCGTATGACACTCATAGCGTATGATCGTATGACGTAATCGTATGACACGTATGACGTATGACTCGTATGACGTATGACTCGTATGATCGTATGACGTATGAGCCGTATGACCGTATGACCGTATGACCCGTATGAACCGTATGACACTTACGTATGAAACGTATGAGCCCCCGTATGACGTATGAACGTATGAAGCACGTATGAAGAGCCGCGTATGAGCCGCAGTGCGTATGAGCTCGTATGACGTATGAACGTATGAGTGTCCCGTATGAAGAAACGTATGACGTATGACGTATGAGCCGTATGATACTCGTATGA"
dna2 = "CGTATGACG"
print (dna1, dna2)
print (subs(dna1, dna2))

print ()
print (cons.__doc__)
print ("datafile: cons_dataset.txt")
dna_consensus, A_profile, C_profile, G_profile, T_profile = cons('cons_dataset.txt')
print (dna_consensus)
print ('A:', " ".join(str(x) for x in A_profile))            
print ('C:', " ".join(str(x) for x in C_profile))            
print ('G:', " ".join(str(x) for x in G_profile))            
print ('T:', " ".join(str(x) for x in T_profile))            

print ()
print (grph.__doc__)
print ("datafile: grph_dataset.txt")
adiacency_list = grph('grph_dataset.txt')
for item in adiacency_list:
    print (item)

print ()
print (iev.__doc__)
couples = "16079 16809 18603 19300 18912 19768"
print (couples)
print (iev(couples))

print ()
print (lcsm.__doc__)
print ("datafile: lcsm_dataset.txt")
start = time.time()
print (lcsm('lcsm_dataset.txt'))
end = time.time()
print (f"execution time in seconds: {end-start}")

print ()
print (lia.__doc__)
k = 5
n = 7
simulations = 10000 # 1000000 to get good approximation 
print (f'k = {k}, n = {n}')
start = time.time()
print (lia(k, n, simulations))
end = time.time()
print (f"execution time in seconds: {end-start}")

print ()
print (mprt.__doc__)
print ("datafile: mprt_dataset.txt")
print (mprt('mprt_dataset.txt'))

print ()
print (mrna.__doc__)
#proteinString = "MGSPKWAGTDMPTFQDYNQEDYEIDKKYHACWGMGQVGSIYDFGARAMKFMYTDFTAPFVPETLQCYTCNLRHRYPYHDNIALTDARANPMCDVSYGFFINNFEIYVRSYCVQPYCSPYQEFWSWRVGIPGVIGDEKHWGYPTWHNFWWSFGELDWEDVQMFCTDMPRIMAYQHMGQTFQRPIWMMYQAQAWYDRHGMMDPWTFTKHTKQWGPFYNRPVWPVSWRKHHARAATNSLWIAVCVVPPERINFATGDINVPEPMPPVFFSSGTSKPYCHHNLEKQSPYDLFYSPYPKCLKSGVCDLFQECAQQLDHWMGIIRKHGVRDQSGEQWQTVWQLHHQEPKHSHATHWEDHEAPKHVAHQAMWFEYICQYSCWVWFRGRLFYHDQCRSIINLTWLRKIHNYEFAPQCWVLRLKRHLSQHMRGDYYIWQKQDICNVAVGTYLRDGRKRNEFCQKYIHMSYSADGGRCAGKQDDMSQPGHHLPMSKRDTWQFWAPRMCCRPITLKGLHDMLCTHNNPPMAIRWANVMFWRIKIPCAAQSAKIEDMKMPYIPCGEGLNFLKSEPLCCETNYFTTFCHKKEIERWKSKVGCCRYAITGNLWKMMYPSNSANPGGRHGVYCWQHPEHLFERWYCECWWEFNTWNDSAKGIHMSHLMVYSWLHKRSRDPKQMINRYQCETKVGEVQQMHAYGTGYNIQIWWGAPKDNSVSQWCSDDAREPDSGVMGKVDYIQAGDVDKKCKDEHWCGLIDSTVTTYFTVWWGSQLPRMPRMNRNGINRVVECWNVICPAFHMHITCYESNRDKFEDREGTVWDYWNPSGHHGQGQKRQLQKRILIMYPKGSLEDPAQNMADWYHLLCNYQNNTWSHNWTVISCIETAMYAGNRQQERAGCRYSWWQHMDEICTACVTDTNHAAHIFFECMEKSWDISCWFSMGIDFAKTEFCRHNLLHNNHSYKSREKVLKEYIPDTSDLASVLPGQSCYHYNNRRIQTQSMGQAMGHHWCQN"
proteinString = "MPWIEAQNKAIISYECNLGSTGDGKPIFPFMWLAQNMFYAKWYFGQTWMKNHKGIWISGQCAVYPNQTRPVDCYMCGEARWKRNQAIAKCVNLLCGREHCCISWRNMTVTDRNSMSWPDLASFIIQRHSMPDSSNVDYFICGGHGSIHYALWFDVNPGCSWDLLASYVWSPPLMGVCITCTCVHCGNNGMSEASYLQANTPRVLEGQCMRFNMCCWNLYEDCMRTWIWGYVVKGEILQPVRPDLNGLELFQFSDCRHVYPIMTTLSSLGYNVLSISTLIECLDDGSNFCEVCELEIGAKIWRLLAFPNDVRMCEEFSVMPVSMMRAQTSVFGQGFETPNRQMTFAPFGLAIKFDQFAHMILKNCLIFALKMDMNITPVAPNQMKPWPLDCLIYDQCGIRRMRSISACAELPGDESYASTMHQGIWNHSWPAYMWQENTLDYSHNMRCCQKEEIFAHKIQSPRRGAKWLDKMLLDKDATLKSCENVGCQVMQILNSFQESTDESFSRYVKNWPCIPFNKFHMCCWSRVQMGPNCVSCDSSMYAYSVQTVDFKMLYFTTIQGGHNPISFQMDAHILKWDFPRNESHKEACCNVSPEPDLDHCGGNWYQQPSRVEPEHDTNYPYGMRVEPLPFYRWEDHCNKEMHQPTQEAIYAGLLQLLGVPSCLSFLSCFAMADEPITLYMTHLQYKWCNMCCIFSAQKVNVNHKGEHSKKFGATFAQPLLPRWYGRWMINFSQMQIPIKESIDPMWAGTTQAVNKIPRDICHFIMMGGCGDLGGQTIHTFMARKWWGCAIPNGLLKEASGCWYQMKDHKQKNMLRVKCGADRVSHFNLWTTIGHHLARHGGQIRKLKPGIRNDRNQLGGQMVVIWDVWCTECKCIEKEHPSFCSDERTCGATIKETRWFQMLVFFTFQEWSNDGLSDCTHLPMCTEGQMIQRVFPAIKEMRNHEVLLLTWQMGFECILYVAKLDILVTPTSNFVTSQKMYPQMACRIEHKHQGCNENKQ"
print (proteinString)
print (mrna(proteinString))

print ()
print (orf.__doc__)
print ("datafile: orf_dataset.txt")
print (orf('orf_dataset.txt'))

print ()
print (perm.__doc__)
n = 7
print (f'n = {n}')
print (perm(n))

print ()
print (prtm.__doc__)
protein = "SKADYEK"
print (protein)
print (prtm(protein))

